server:
  port: 7081
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    database-platform:
      org.hibernate.dialect.MySQLDialect
    show-sql:
      true

  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled:
        false
    jdbc:
      initialize-schema:
        ALWAYS
  main:
    allow-bean-definition-overriding:
      true
